- hosts: localhost
  gather_facts: no
  tasks:

  - name: Drupal Settings
    k8s:
      definition:
        kind: ConfigMap
        apiVersion: v1
        metadata:
          name: '{{ meta.name }}-drupal-config'
          namespace: '{{ meta.namespace }}'
        data:
          settings.php: |-
            <?php
            
            $databases['default']['default'] = array(
              'database' => 'drupal',
              'username' => 'drupal',
              'password' => 'drupal',
              'prefix' => '',
              'host' => '127.0.0.1',
              'port' => '3306',
              'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
              'driver' => 'mysql',
            );
            
            $settings['hash_salt'] = '{{ hash_salt | default(lookup('password', '/dev/null chars=ascii_letters'), true) }}';
            $settings['trusted_host_patterns'] = ['{{ trusted_host_patterns | default('^.+$', true) }}'];

  - name: Files PVC
    k8s:
      definition:
        kind: PersistentVolumeClaim
        apiVersion: v1
        metadata:
          name: '{{ meta.name }}-files-pvc'
          namespace: '{{ meta.namespace }}'
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: '{{ files_pvc }}'

  - name: Mariadb PVC
    k8s:
      definition:
        kind: PersistentVolumeClaim
        apiVersion: v1
        metadata:
          name: '{{ meta.name }}-db-pvc'
          namespace: '{{ meta.namespace }}'
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: '{{ db_pvc }}'

  - name: Drupal
    k8s:
      definition:
        kind: Deployment
        apiVersion: apps/v1
        metadata:
          name: '{{ meta.name }}-drupal'
          namespace: '{{ meta.namespace }}'
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: drupal
          template:
            metadata:
              labels:
                app: drupal
            spec:
              initContainers:
                - name: checkout
                  image: alpine/git
                  command:
                    - git
                    - clone
                    - --branch 
                    - '{{ git.branch }}'
                    - --single-branch
                    - --depth
                    - '1'
                    - '{{ git.repo }}'
                    - /app/drupal
                  volumeMounts:
                  - name: drupal-code
                    mountPath: /app/drupal/
                - name: composer
                  image: composer
                  command: 
                    - composer
                    - install
                    - --working-dir=/app/drupal
                    - --no-dev
                    - --ignore-platform-reqs
                  env:
                  - name: COMPOSER_CACHE_DIR
                    value: /composer/cache
                  volumeMounts:
                  - name: drupal-code
                    mountPath: /app/drupal/
                  - name: cache-volume
                    mountPath: /composer/cache/
              containers:
              - name: drupal
                image: "drupal:{{ version }}-apache"
                ports:
                  - containerPort: 80
                livenessProbe:
                  tcpSocket:
                    port: 80
                  initialDelaySeconds: 60
                readinessProbe:
                  tcpSocket:
                    port: 80
                  initialDelaySeconds: 30
                volumeMounts:
                - name: drupal-code
                  mountPath: /var/www/html/
                - name: drupal-settings
                  mountPath: /var/www/html/sites/default/
                - name: drupal-files
                  mountPath: /var/www/html/sites/default/files/
              - name: mariadb
                image: "mariadb"
                ports:
                  - containerPort: 3306
                env:
                  - name: MYSQL_DATABASE
                    value: drupal
                  - name: MYSQL_USER
                    value: drupal
                  - name: MYSQL_PASSWORD
                    value: drupal
                  - name: MYSQL_RANDOM_ROOT_PASSWORD
                    value: "yes"
                volumeMounts:
                - mountPath: /var/lib/mysql/
                  name: drupal-db
              volumes:
                - name: drupal-code
                  emptyDir: {}
                - name: drupal-settings
                  configMap:
                    name: '{{ meta.name }}-drupal-config'
                - name: drupal-files
                  persistentVolumeClaim:
                    claimName: '{{ meta.name }}-files-pvc'
                - name: drupal-db
                  persistentVolumeClaim:
                    claimName: '{{ meta.name }}-db-pvc'
                - name: cache-volume
                  hostPath:
                    path: /data/composer

  - name: Drupal Service
    k8s:
      definition:
        kind: Service
        apiVersion: v1
        metadata:
          name: '{{ meta.name }}-service'
          namespace: '{{ meta.namespace }}'
        spec:
          type: NodePort
          ports:
            - port: 80
              targetPort: 80
          selector:
            app: 'drupal'
