- hosts: localhost
  gather_facts: no
  tasks:

  - name: Drupal Settings
    k8s:
      definition:
        kind: ConfigMap
        apiVersion: v1
        metadata:
          name: '{{ meta.name }}-drupal-config'
          namespace: '{{ meta.namespace }}'
        data:
          settings.php: |-
            <?php
            
            $databases['default']['default'] = array(
              'database' => 'drupal',
              'username' => 'drupal',
              'password' => 'drupal',
              'prefix' => '',
              'host' => '{{ meta.name }}-db',
              'port' => '3306',
              'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
              'driver' => 'mysql',
            );
            
            $settings['hash_salt'] = 'changeme';
            $settings['trusted_host_patterns'] = ['^.+$'];

  - name: Drupal PVC
    k8s:
      definition:
        kind: PersistentVolumeClaim
        apiVersion: v1
        metadata:
          name: '{{ meta.name }}-drupal-pvc'
          namespace: '{{ meta.namespace }}'
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

  - name: Drupal
    k8s:
      definition:
        kind: Deployment
        apiVersion: apps/v1
        metadata:
          name: '{{ meta.name }}-drupal'
          namespace: '{{ meta.namespace }}'
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: drupal
          template:
            metadata:
              labels:
                app: drupal
            spec:
              containers:
              - name: drupal
                image: "drupal:{{ version }}-apache"
                ports:
                  - containerPort: 80
                volumeMounts:
                - mountPath: /var/www/html/sites/default/
                  name: drupal-settings
                - mountPath: /var/www/html/sites/default/files/
                  name: drupal-files
                livenessProbe:
                  tcpSocket:
                    port: 80
                  initialDelaySeconds: 60
                readinessProbe:
                  tcpSocket:
                    port: 80
                  initialDelaySeconds: 30           
              volumes:
                - name: drupal-settings
                  configMap:
                    name: '{{ meta.name }}-drupal-config'
                - name: drupal-files
                  persistentVolumeClaim:
                    claimName: '{{ meta.name }}-drupal-pvc'

  - name: Drupal Service
    k8s:
      definition:
        kind: Service
        apiVersion: v1
        metadata:
          name: '{{ meta.name }}-service'
          namespace: '{{ meta.namespace }}'
        spec:
          type: NodePort
          ports:
            - port: 80
              targetPort: 80
          selector:
            app: 'drupal'

  - name: Mariadb PVC
    k8s:
      definition:
        kind: PersistentVolumeClaim
        apiVersion: v1
        metadata:
          name: '{{ meta.name }}-db-pvc'
          namespace: '{{ meta.namespace }}'
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

  - name: Mariadb
    k8s:
      definition:
        kind: Deployment
        apiVersion: apps/v1
        metadata:
          name: '{{ meta.name }}-db'
          namespace: '{{ meta.namespace }}'
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: mariadb
          template:
            metadata:
              labels:
                app: mariadb
            spec:
              containers:     
              - name: mariadb
                image: "mariadb"
                ports:
                  - containerPort: 3306
                volumeMounts:
                - mountPath: /var/lib/mysql/
                  name: drupal-db                            
                env:
                  - name: MYSQL_DATABASE
                    value: drupal
                  - name: MYSQL_USER
                    value: drupal
                  - name: MYSQL_PASSWORD
                    value: drupal
                  - name: MYSQL_RANDOM_ROOT_PASSWORD
                    value: "yes"
              volumes:
                - name: drupal-db
                  persistentVolumeClaim:
                    claimName: '{{ meta.name }}-db-pvc'

  - name: Mariadb Service
    k8s:
      definition:
        kind: Service
        apiVersion: v1
        metadata:
          name: '{{ meta.name }}-db'
          namespace: '{{ meta.namespace }}'
        spec:
          type: NodePort
          ports:
            - port: 3306
              targetPort: 3306
          selector:
            app: 'mariadb'
