---
galaxy_info:
  author: Jeff Geerling
  description: Drupal deployment inside Kubernetes.
  company: Midwestern Mac, LLC

  license: MIT

  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - drupal
    - cms
    - web
    - application
    - website
    - operator

dependencies: []
