apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: drupals.drupal.drupal.org
spec:
  group: drupal.drupal.org
  names:
    kind: Drupal
    listKind: DrupalList
    plural: drupals
    singular: drupal
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
