apiVersion: drupal.drupal.org/v1alpha1
kind: Drupal
metadata:
  name: example-drupal
spec:
  drupal_version: '8.7'
  files_pvc_size: 1Gi
  manage_database: true
  database_image: mariadb:10
  database_pvc_size: 1Gi
