apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: drupal-operator
  template:
    metadata:
      labels:
        name: drupal-operator
    spec:
      serviceAccountName: drupal-operator
      containers:
        - name: drupal-operator
          image: "8thom/drupal-operator:v0.0.1"
          imagePullPolicy: "Always"
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "drupal-operator"
