---

- name: Verify
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    deploy_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/deploy"
    custom_resource: "{{ lookup('file', '/'.join([deploy_dir, 'crds/drupal_v1alpha1_drupal_cr.yaml'])) | from_yaml }}"
  tasks:
    - name: Get all pods in {{ custom_resource.metadata.namespace }}
      k8s_facts:
        api_version: v1
        kind: Pod
        namespace: '{{ custom_resource.metadata.namespace }}'
      register: pods

    - name: Output pods
      debug: var=pods

    # TODO: Verify you can reach Drupal's installer at the NodePort.
    # TODO: Maybe even run Drupal's installer?
