---

- name: Verify
  hosts: k8s
  gather_facts: false
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    deploy_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/deploy"
    custom_resource: "{{ lookup('file', '/'.join([deploy_dir, 'crds/drupal_v1alpha1_drupal_cr.yaml'])) | from_yaml }}"
  tasks:
    - name: Get all pods in {{ custom_resource.metadata.namespace }}
      k8s_info:
        api_version: v1
        kind: Pod
        namespace: '{{ custom_resource.metadata.namespace }}'
      register: pods
      delegate_to: localhost

    - name: Output pods
      debug: var=pods

    - name: Get drupal service
      k8s:
        kind: Service
        api_version: v1
        name: "{{ custom_resource.metadata.name }}"
        namespace: "{{ custom_resource.metadata.namespace }}"
      register: drupal_service
      delegate_to: localhost

    - name: Verify Drupal installer loads
      uri:
        url: "http://localhost:{{ drupal_service.result.spec.ports[0].nodePort }}/core/install.php"
        status_code: 200
      vars:
        ansible_python_interpreter: python

    # TODO: Maybe install Drupal?
