---
drupal_image: 'drupal:8.8-apache'
# You should generate your own hash salt, e.g. `Crypt::randomBytesBase64(55)`.
drupal_hash_salt: ''
drupal_trusted_host_patterns: ''
files_pvc_size: 1Gi

# Database options (will be used regardless of database location).
database_driver: mysql
database_name: drupal
database_username: drupal
database_password: drupal
database_prefix: ''
database_host: 'example-drupal-mariadb'
database_port: 3306

# Set this to 'true' to use a single-pod database managed by this operator.
manage_database: true
database_image: mariadb:10
database_pvc_size: 1Gi

# Set this to 'true' to have this operator manage Ingress for the site.
manage_ingress: true
drupal_hostname: example-drupal.test
